<?php

namespace AppBundle\Repository;

/**
 * championRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class championRepository extends \Doctrine\ORM\EntityRepository
{
}
