<?php

namespace AppBundle\Repository;

/**
 * matchesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matchesRepository extends \Doctrine\ORM\EntityRepository
{
}
