<?php

namespace AppBundle\Repository;

/**
 * matches1x1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matches1x1Repository extends \Doctrine\ORM\EntityRepository
{
}
